src/SmartFormat.Tests/Extensions/PluralLocalizationFormatterTests.cs, src/SmartFormat/Extensions/PluralLocalizationFormatter.cs
=> added support for ushort, uint, and ulong to PluralLocalizationFormatter

src/SmartFormat.Tests/Core/ParserTests.cs
=> Implemented tests for the different ParserErrorActions

src/SmartFormat.Tests/Core/FormatterTests.cs, src/SmartFormat.Tests/Core/ParserTests.cs, src/SmartFormat.Tests/SmartFormat.Tests.csproj, src/SmartFormat/Core/Parsing/Parser.cs, src/SmartFormat/SmartFormat.csproj
=> Fully implement parse error actions

src/SmartFormat/Extensions/ReflectionSource.cs
* Added reflection cache
* Update for instance/class variables
Co-authored-by: axunonb <nb@axuno.net>
=> Reflection cache (#155)

src/SmartFormat/Utilities/PluralRules.cs
Fixes #179 (DualFromZeroToTwo plural rule) thanks to @OhSoGood
=> Fixes #179

CHANGES.md, appveyor.yml, src/Directory.Build.props, src/SmartFormat/Core/Parsing/Parser.cs, src/SmartFormat/Extensions/ConditionalFormatter.cs, src/SmartFormat/Extensions/JsonSource.cs, src/SmartFormat/Extensions/PluralLocalizationFormatter.cs, src/SmartFormat/SmartFormat.csproj
* **Fixed**: `ConditionalFormatter` processes unsigned numbers in arguments correctly.
* **Fixed**: `JsonSource`: Corrected handling of `null` values in NewtonSoftJson objects.
=> Bumped version to v2.7.2

src/SmartFormat.ZString/ZStringBuilder.cs, src/SmartFormat.ZString/repo/sandbox/PerfBenchmark/Benchmarks/StringBuilderAppendFormat.cs, src/SmartFormat.ZString/repo/src/ZString.Unity/Assets/Scripts/ZString/FormatParser.cs, src/SmartFormat.ZString/repo/src/ZString.Unity/Assets/Scripts/ZString/PreparedFormatHelper.cs, src/SmartFormat.ZString/repo/src/ZString.Unity/Assets/Scripts/ZString/Utf16/Utf16ValueStringBuilder.AppendFormat.cs, src/SmartFormat.ZString/repo/src/ZString.Unity/Assets/Scripts/ZString/Utf8/Utf8ValueStringBuilder.AppendFormat.cs, src/SmartFormat.ZString/repo/src/ZString.Unity/Assets/Scripts/ZString/Utf8ValueStringBuilder.cs, src/SmartFormat.ZString/repo/src/ZString.Unity/Assets/Scripts/ZString/ZString.Format.cs, src/SmartFormat.ZString/repo/src/ZString.Unity/Assets/Scripts/ZString/package.json, src/SmartFormat.ZString/repo/src/ZString/FormatParser.cs, src/SmartFormat.ZString/repo/src/ZString/PreparedFormatHelper.cs, src/SmartFormat.ZString/repo/src/ZString/Utf16/Utf16ValueStringBuilder.AppendFormat.cs, src/SmartFormat.ZString/repo/src/ZString/Utf16/Utf16ValueStringBuilder.AppendFormat.tt, src/SmartFormat.ZString/repo/src/ZString/Utf8/Utf8ValueStringBuilder.AppendFormat.cs, src/SmartFormat.ZString/repo/src/ZString/Utf8/Utf8ValueStringBuilder.AppendFormat.tt, src/SmartFormat.ZString/repo/src/ZString/Utf8ValueStringBuilder.cs, src/SmartFormat.ZString/repo/src/ZString/ZString.Format.cs, src/SmartFormat.ZString/repo/src/ZString/ZString.Format.tt
Add ReadOnlySpan<char> api for AppendFormat in SmartFormat.ZString.ZStringBuilder
=> Upgrade to CySharp.ZString v2.4.4

src/Demo.NetFramework/Sample Extensions/ArgumentValidator.cs, src/Demo.NetFramework/Sample Extensions/EnumerableExtensions.cs, src/Demo/Sample Extensions/ArgumentValidator.cs, src/Demo/Sample Extensions/EnumerableExtensions.cs, src/Directory.Build.props, src/SmartFormat.Deploy.sln, src/SmartFormat.Extensions.Newtonsoft.Json/SmartFormat.Extensions.Newtonsoft.Json.csproj, src/SmartFormat.Extensions.System.Text.Json/SmartFormat.Extensions.System.Text.Json.csproj, src/SmartFormat.Extensions.Time/SmartFormat.Extensions.Time.csproj, src/SmartFormat.Extensions.Xml/SmartFormat.Extensions.Xml.csproj, src/SmartFormat.Net/SmartFormat.Net.csproj, src/SmartFormat.Tests/Extensions/ListFormatterTests.cs, src/SmartFormat/SmartFormat.csproj
=> Fix for continuous integration

appveyor.yml
Update NuGet API Key in appveyor.yml
=> Update NuGet API Key

.github/workflows/SonarCloud.yml, README.md, appveyor.yml, src/Directory.Build.props
Update version number
Update README.md
=> Bump version to v3.3.1

appveyor.yml
=> Fix: Update nuget api key

appveyor.yml
[![AppVeyor tests](https://img.shields.io/appveyor/tests/axuno/SmartFormat.svg)](https://ci.appveyor.com/project/axuno/SmartFormat/branch/main/tests)
=> chore: Add appveyor logger for CI tests

.github/dependabot.yml, README.md
* Add `dependabot.yml` to configure Dependabot in the GitHub repository.
* Update README
=> chore: Add GitHub Dependabot configuration

src/SmartFormat.Tests/Core/FormatterTests.cs, src/SmartFormat/Core/Formatting/FormatDetails.cs, src/SmartFormat/Core/Formatting/FormattingInfo.cs, src/SmartFormat/Core/Formatting/ISelectorInfo.cs, src/SmartFormat/SmartFormatter.cs
chore: Update comments and xmldoc
=> test: Add unit test for nested scope

.github/workflows/CheckWikiUpdates.yml, .github/workflows/Wiki_Update_Issue_Template.md
* Update to `JasonEtco/create-an-issue@v2.9.2`
* Create issue with label `Docs`
* Show number of commits in the last 24 hours
* Show details about the latest commit
=> chore: Update action for Wiki update tracking

.github/workflows/CheckWikiUpdates.yml, .github/workflows/SonarCloud.yml, .github/workflows/Wiki_Update_Issue_Template.md, appveyor.yml
* Add files to ignore
* Add condition when to run
=> chore: Improve CI

src/SmartFormat.Extensions.LogiCalc/LogiCalcFormatter.cs, src/SmartFormat.Extensions.LogiCalc/SmartFormat.Extensions.LogiCalc.csproj, src/SmartFormat.Tests/Extensions.LogiCalc/LogiCalcFormatterTests.cs
Use updated API like described at https://github.com/ncalc/ncalc/releases/tag/v5.0.0
=> Upgrade to NCalc v5.0.0

.github/workflows/CheckWikiUpdates.yml
Reasoning: runner error for special characters
=> chore: Url-encode special characters in the commit message

src/SmartFormat.Extensions.Time/TimeFormatter.cs, src/SmartFormat.Extensions.Time/Utilities/TimeSpanUtility.cs, src/SmartFormat.Extensions.Time/Utilities/TimeTextInfo.cs, src/SmartFormat.Tests/Core/FormatterTests.cs, src/SmartFormat.Tests/Core/ParserTests.cs, src/SmartFormat.Tests/EvaluatorTests.cs, src/SmartFormat.Tests/Extensions/ReflectionSourceTests.cs, src/SmartFormat.Tests/Extensions/StringSourceTests.cs, src/SmartFormat.Tests/Extensions/ValueTupleSourceTests.cs, src/SmartFormat.Tests/Pooling/PoolPolicyTests.cs, src/SmartFormat.Tests/TestUtils/Address.cs, src/SmartFormat/Core/Parsing/SplitList.cs, src/SmartFormat/Extensions/StringSource.cs
- Replaced Any() with Count != 0 for better performance. 
- Updated parameter types in TimeTextInfo.cs and EvaluatorTests.cs. 
- Simplified assertion syntax in multiple test files. 
- Changed Enum.Parse to Enum.TryParse in Address.cs. 
- Converted instance methods to static in StringSource.cs.
=> Code Style Housekeeping

.github/workflows/CodeQuality.yml, appveyor.yml
- SonarCloud integration
- CodeCov integration
- Disabled respective scripts in appveyor.yml
=> Move code quality CI to Github Action CodeQuality.yml
