src/SmartFormat.Tests/Extensions/PluralLocalizationFormatterTests.cs
src/SmartFormat/Extensions/PluralLocalizationFormatter.cs

If given, the number of items in the IEnumerable will be used. This allows
``` csharp
Smart.Format("The following {0:plural:person is|people are} impressed: {0:list:{}|, |, and}", people);
```
rather than:
``` csharp
Smart.Format("The following {1:plural:person is|people are} impressed: {0:list:{}|, |, and}", people, people.Count);
```

Allow PluralLocalizationFormatter to accept an IEnumerable argument

---

src/SmartFormat.Tests/Extensions/SubStringFormatterTests.cs
src/SmartFormat/Extensions/SubStringFormatter.cs

if specified length is longer than input length, set length to the maximum possible length
fixes #141
```	
var people = new List<object>
{new {Name = "Long John", City = "New York"}, new {Name = "Short Mary", City = "Massachusetts"},};
Smart.Format("{Name:substr(5)}", people.First());
// result: "John"
Smart.Format("{City:substr(0,3)}", people.First());
// result: "New"
Smart.Format("{City:substr(999,0)}", people.First());
// result: ""
Smart.Format("{City:substr(0,999)}", people.First());
// result: "New York"
```

Makes sure that substring outputs the entire string (or what's left of it), instead of "", if the specified length is to great.

---

README.md
src/SmartFormat.Tests/Core/ParserTests.cs
src/SmartFormat.Tests/SmartFormat.Tests.csproj
src/SmartFormat/Core/Parsing/LiteralText.cs
src/SmartFormat/Core/Parsing/Parser.cs
src/SmartFormat/Core/Parsing/ParsingErrors.cs
src/SmartFormat/SmartFormat.csproj

This PR addresses issues referenced in #148, #147, #143.
**Also fixed:**
If the last item of a format string was an uncompleted `Placeholder` (e.g. ending `"like {uncomplete"`), the parser now takes it as an erroneous `Placeholder`, not as a `TextLiteral` (as it was the case until v2.6.2).
---
@andersjonsson @nikita-starostin @hugoqribeiro: Your feedback on this PR would be appreciated.
> Here is the draft package of `SmartFormat.NET.2.7.0-preview-1` (not published yet, more to come):
[SmartFormat.NET.2.7.0-preview-1.zip](https://github.com/axuno/SmartFormat/files/6250870/SmartFormat.NET.2.7.0-preview-1.zip)
@andersjonsson @nikita-starostin Since v2.6.2 the following issue is breaking backward-compatibility:
**`Parser.ErrorAction.MaintainTokens`**: If one of serveral `Placeholder`s has …

Fix parsing issues

---

CHANGES.md
src/SmartFormat.Performance/ReflectionVsStringSource.cs
src/SmartFormat.Tests/Extensions/ListFormatterTests.cs
src/SmartFormat.Tests/Extensions/ReflectionFormatterTests.cs
src/SmartFormat.Tests/Extensions/StringSourceTests.cs
src/SmartFormat/Extensions/DefaultSource.cs
src/SmartFormat/Extensions/ReflectionSource.cs
src/SmartFormat/Extensions/StringSource.cs
src/SmartFormat/Smart.cs

`StringSource` adds the following selector names, which have before been implemented with `ReflectionSource`:
* Length
* ToUpper
* ToUpperInvariant
* ToLower
* ToLowerInvariant
* Trim
* TrimStart
* TrimEnd
* ToCharArray
Additionally, the following selector names are implemented:
* Capitalize
* CapitalizeWords
* FromBase64
* ToBase64
All these selector names may linked. Example with indexed placeholders:
```CSharp
Smart.Format("{0.ToLower.TrimStart.TrimEnd.ToBase64}", " ABCDE ");
// result: "YWJjZGU="
```
This also works for named placeholders.
**Note**: `ReflectionSource` does not evaluate `string`s any more.
The new formatter privates additional funcionality and with with reflection caching, performance is 13% better.
```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
AMD Ryzen 9 3900X, …
```

String as i source

---

src/SmartFormat.Tests/Core/LiteralTextTests.cs
src/SmartFormat.Tests/Core/NamedFormatterTests.cs
src/SmartFormat.Tests/Core/NestingTests.cs
src/SmartFormat.Tests/Core/SmartStaticTests.cs
src/SmartFormat.Tests/Extensions/ChooseFormatterTests.cs
src/SmartFormat.Tests/Extensions/ConditionalFormatterTests.cs
src/SmartFormat.Tests/Extensions/ListFormatterTests.cs
src/SmartFormat.Tests/Extensions/PluralLocalizationFormatterTests.cs
src/SmartFormat.Tests/Extensions/ReflectionFormatterTests.cs
src/SmartFormat.Tests/Extensions/SystemTextJsonSourceTests.cs
src/SmartFormat.Tests/Extensions/TimeFormatterTests.cs
src/SmartFormat.Tests/Extensions/XmlSourceTest.cs
src/SmartFormat.Tests/Utilities/FormatDelegateTests.cs

* No more class instance variables for SmartFormatter
* No usage of static Smart.Format methods
* No usage of static Smart.Default
Now all tests can run in any sequence without any mutual interference

Removed all shared or default formatters from tests

---

src/SmartFormat.Tests/Extensions/DefaultSourceTests.cs
src/SmartFormat.Tests/Extensions/KeyValuePairSourceTests.cs
src/SmartFormat.Tests/SmartFormat.Tests.csproj
src/SmartFormat/Extensions/KeyValuePairSource.cs
src/SmartFormat/Extensions/WellKnownExtensionTypes.cs
src/SmartFormat/Smart.cs
src/SmartFormat/SmartFormatter.cs

Added `KeyValuePairSource` as a simple, cheap and performant way to create named placeholders.
Example:
```Csharp
Smart.Format("{placeholder}", new KeyValuePair<string, object?>("placeholder", "some value")
// Result: "some value"
```

Add KeyValuePairSource as another ISource extension

---

CHANGES.md
src/SmartFormat.Tests/Core/LiteralTextTests.cs
src/SmartFormat.Tests/Core/ParserTests.cs
src/SmartFormat.Tests/Core/StringFormatCompatibilityTests.cs
src/SmartFormat.Tests/Extensions/ListFormatterTests.cs
src/SmartFormat/Core/Parsing/Parser.cs
src/SmartFormat/Core/Settings/ErrorAction.cs
src/SmartFormat/Core/Settings/SmartSettings.cs
src/SmartFormat/Extensions/WellKnownExtensionTypes.cs

* Fix: A single escape character at the end of the input string will now throw an `ArgumentException` with a comprehensive error message.
* Remainders from the v2.x API: All obsolete element usage creates a compile time error
* Updates for CHANGES.md

Bugfix in Parser. Obsolete elements throw compile time errors.

---

CHANGES.md
README.md
src/SmartFormat.Tests/Core/EscapedLiteralTests.cs
src/SmartFormat.Tests/Core/LiteralTextTests.cs
src/SmartFormat.Tests/Extensions/IsMatchFormatterTests.cs
src/SmartFormat.Tests/SmartFormat.Tests.csproj
src/SmartFormat/Core/Parsing/EscapedLiteral.cs

Fix: Table of characters, that must be escaped with a backslash
* Removed ' and " => no escaping
* Added { and } => must always be escaped - added to be complete
* Chars to be escaped in Options: only ( and )

Fix characters to be escaped

---

src/SmartFormat.Tests/Extensions/ConditionalFormatterTests.cs
src/SmartFormat/Extensions/ConditionalFormatter.cs
src/SmartFormat/Extensions/PluralLocalizationFormatter.cs

An implementation of a magic leading colon in order to identify whether `ConditionalFormatter` or `PluralLocalizationFormatter` should be invoked, was removed.
**Reasoning:**
This is an undocumented and unnecessary code smell. 
Adding the formatter name in the format string fulfills the same target.

Remove magic leading colon for ConditionalFormatter

---

CHANGES.md
src/SmartFormat.Tests/Extensions/ChooseFormatterTests.cs
src/SmartFormat.Tests/Extensions/LocalizationFormatterTests.cs
src/SmartFormat.Tests/Extensions/PersistentVariableSourceTests.cs
src/SmartFormat.Tests/Extensions/VariablesGroupTests.cs
src/SmartFormat/Extensions/ChooseFormatter.cs

Modified `ChooseFormatter` case-sensitivity for option strings. This modification is compatible with v2.
* `bool` and `null` as string: always case-insensitive
* using `SmartSettings.CaseSensitivity` unless overridden with `ChooseFormatter.CaseSensitivity`
* option strings comparison is culture-aware (using `CultureInfo` arg to `Smart.Format(...)` or `CurrentUICulture`

Pr choose fmt options case sensitivity

---

CHANGES.md
src/SmartFormat.Tests/Extensions/ChooseFormatterTests.cs
src/SmartFormat.Tests/Extensions/ConditionalFormatterTests.cs
src/SmartFormat.Tests/Extensions/IsMatchFormatterTests.cs
src/SmartFormat.Tests/Extensions/ListFormatterTests.cs
src/SmartFormat.Tests/Extensions/PluralLocalizationFormatterTests.cs
src/SmartFormat/Core/Parsing/LiteralText.cs
src/SmartFormat/Core/Settings/PoolSettings.cs
src/SmartFormat/Extensions/ChooseFormatter.cs
src/SmartFormat/Extensions/ConditionalFormatter.cs
src/SmartFormat/Extensions/IsMatchFormatter.cs
src/SmartFormat/Extensions/ListFormatter.cs
src/SmartFormat/Extensions/NullFormatter.cs
src/SmartFormat/Extensions/PluralLocalizationFormatter.cs
src/SmartFormat/Extensions/SubStringFormatter.cs
src/SmartFormat/Utilities/Validation.cs

* Char to split options and formats is limited to pipe, comma, tilde
* SplitChar for formatters is unified and checked for validity
* Affects ChooseFormatter, ConditionalFormatter, IsMatchFormatter, ListFormatter, PluralLocalizationFormatter, SubStringFormatter

Char to split options and formats is limited to pipe, comma, tilde

---

src/SmartFormat.Tests/Extensions/KeyValuePairSourceTests.cs
src/SmartFormat/Extensions/KeyValuePairSource.cs
src/SmartFormat/Extensions/WellKnownExtensionTypes.cs

KeyValuePairSource can process Nullable Notation
This is only required, if it is the only registered `ISource`

KeyValuePairSource can process nullable notation

---

CHANGES.md
src/SmartFormat.Tests/Extensions/SubStringFormatterTests.cs
src/SmartFormat/Extensions/SubStringFormatter.cs

The only syntax in v2:
> **{ string : substr(*start*,*length*)** **}**
Added optional *format-placeholder* in v3
> **{ string : substr(*start*,*length*)** *: {format-placeholder}* **}**
*value*: Only strings can be processed. Other objects cause a `FormattingException`.
*arguments*: The start position and the lenght of the sub-string.
**NEW**
*format-placeholder*: A nested `Placeholder` that lets you format the result of the sub-string operation.
The Format argument *must* contain nested `Placeholder`, and *may* contain literal text.
**Convert the substring to lower-case**
```CSharp
Smart.Format("{0:substr(0,2):{ToLower}}", "ABC");
//                          |        |
//                          + format +
//                             arg
// Outputs: "ab"
```
**Format the substring …

Added 'format' argument so the result of the substr can be processed

---

CHANGES.md
src/SmartFormat.Extensions.Newtonsoft.Json/NewtonsoftJsonSource.cs
src/SmartFormat.Extensions.System.Text.Json/SystemTextJsonSource.cs
src/SmartFormat.Tests/Extensions/PersistentVariableSourceTests.cs
src/SmartFormat/Core/Sources/Source.cs
src/SmartFormat/Extensions/DictionarySource.cs
src/SmartFormat/Extensions/KeyValuePairSource.cs
src/SmartFormat/Extensions/PersistentVariablesSource.cs
src/SmartFormat/Extensions/ReflectionSource.cs
src/SmartFormat/Extensions/StringSource.cs

1. `PersistentVariablesSource` can process `nullable` operator `?.`
2. Added method Source.TrySetResultForNullableOperator(ISelectorInfo selectorInfo)
* Call this method from all `ISource`s except `DefaultSource`

PersistentVariablesSource can process nullable operator

---

src/SmartFormat.Tests/Extensions/ListFormatterTests.cs
src/SmartFormat/Extensions/ListFormatter.cs

As discussed in https://github.com/axuno/SmartFormat/issues/279
This adds support for using formatting on all the spacers of a list.
I removed the null spacer as from what I can see it would never happen because `parameters.Count` will always be at least 2, we exit the code if its not earlier on.

Feature: Nested formatting inside of List spacers 

---

CHANGES.md
README.md
src/Directory.Build.props
src/SmartFormat.Tests/Core/FormatterTests.cs
src/SmartFormat.Tests/Extensions/ListFormatterTests.cs
src/SmartFormat.Tests/SmartFormat.Tests.csproj
src/SmartFormat/Core/Settings/SmartSettings.cs
src/SmartFormat/Pooling/PoolRegistry.cs
src/SmartFormat/Pooling/SpecializedPools/SpecializedPoolAbstract.cs
src/SmartFormat/Smart.cs
src/SmartFormat/SmartFormatter.cs

Thread-safe mode is now enabled by default:
`SmartSettings.IsThreadSafeMode == true`.<br/>
This has no impact on the API.
In case *SmartFormat* is *exclusively* utilized in a single-threaded context, `SmartSettings.IsThreadSafeMode=false` should be considered for enhanced performance.
Static `Smart` methods like Smart.Format(*format*, *args*) can now be called in an `async` / multi-threaded context.
The `SmartFormatter` instance returned by `Smart.Default` is flagged with the `ThreadStatic` attribute.
Thanks to **[karljj1](https://github.com/axuno/SmartFormat/commits?author=karljj1)** for the PR.
Before *v3.1.0* the format options for `ListFormatter` could only contain literal text. Now `Placeholder`s are allowed.
```CSharp
var args = new {
Names = new[] { "John", "Mary", "Amy" },
IsAnd = …
```

Features for upcoming v3.1.0

---

src/SmartFormat.Extensions.Time/Utilities/TimeSpanFormatOptions.cs
src/SmartFormat.Extensions.Time/Utilities/TimeSpanFormatOptionsConverter.cs
src/SmartFormat.Extensions.Time/Utilities/TimeSpanUtility.cs
src/SmartFormat/Utilities/Validation.cs

Hey. 2 very small refactors I added in our version.
1. Don't recreate the valid chars array each time in Validation.
2. Added `TimeSpanFormatOptionsPresets` so that internal use values are not exposed in the public enum. This is particularly important to us as we show the contents of the Enum in a dropdown selector for users and having internal use values would cause confusion.

Refactor suggestions

---

README.md
src/SmartFormat.Tests/Core/FormatterTests.cs
src/SmartFormat.Tests/Core/SourceExtensionsTests.cs
src/SmartFormat.Tests/Extensions/GlobalVariableSourceTests.cs
src/SmartFormat.Tests/Extensions/ListFormatterTests.cs
src/SmartFormat.Tests/Extensions/PersistentVariableSourceTests.cs
src/SmartFormat.Tests/Extensions/ReflectionSourceTests.cs
src/SmartFormat.Tests/Pooling/ConcurrentPoolingTests.cs
src/SmartFormat.Tests/Pooling/StringBuilderPoolTests.cs
src/SmartFormat.Tests/TestSetup.cs
src/SmartFormat.Tests/TestUtils/ThreadSafeMode.cs
src/SmartFormat/Extensions/ReflectionSource.cs

* Removed usage of System.Reflection
* All changes to SmartSettings.IsThreadSafeMode are performed by SmartFormat.Tests.TestUtils.ThreadSafeMode methods

Refactored unit tests for ReflectionSource and thread-safe mode

---

src/SmartFormat/SmartFormatter.cs

A small simplification when checking the type, we use `is` now instead of checking twice.

Use `is` instead of checking the type info.

---

src/SmartFormat.Tests/Extensions/ConditionalFormatterTests.cs
src/SmartFormat.Tests/Extensions/PluralLocalizationFormatterTests.cs
src/SmartFormat.Tests/TestUtils/ConvertibleDecimal.cs
src/SmartFormat/Extensions/ConditionalFormatter.cs
src/SmartFormat/Extensions/PluralLocalizationFormatter.cs

This is something we added for one of our users. 
We want to be able to pass in a class instance that contains various metadata and let it be evaluated against the plural and conditional formatters. At the moment they have to add another field and do something like `{tag.NumberValue:cond:<0?a|b}` however this makes it more complicated for translators to work with, having the extra NumberValue field. 
The `IConvertible` interface has a method for converting to Decimal, in fact, it's whats `Convert.ToDecimal` uses. It also turns out that all the primitive numbers implement this interface so it makes the code a bit simpler and maybe even more performant.
I had to add some exceptions for DateTime, bool, and string as they produce different results.

IConvertible support for plural and conditional formatters

---

src/SmartFormat.Tests/TestUtils/ConvertibleDecimal.cs
src/SmartFormat/Core/Parsing/Format.cs
src/SmartFormat/Core/Parsing/FormatItem.cs
src/SmartFormat/Core/Sources/Source.cs
src/SmartFormat/Extensions/DefaultFormatter.cs
src/SmartFormat/Extensions/ListFormatter.cs
src/SmartFormat/SmartFormatter.cs

* Fixed: FormatItem.AsSpan() now returns ReadOnlySpan<char>.Empty for EndIndex <= StartIndex
* Partly disable SonarClooud warning S3267
* Updated comments and xmldoc
* Refactored IConvertible unit tests

Fixed: FormatItem.AsSpan()

---

src/SmartFormat/Extensions/ListFormatter.cs

* Set the `ParentPlaceholder` property for item `Format`s
* Use `PooledObject<T>` where possible, so objects will be returned to `ObjectPool` also in case of exceptions

Refactor ListFormatter

---

src/SmartFormat.Tests/Extensions/PluralLocalizationFormatterTests.cs
src/SmartFormat/Extensions/PluralLocalizationFormatter.cs

I introduced a small bug in my last PR. The plurals formatter will now also consider bools which changes the behaviors when it is using auto detect. This was causing some of our tests to fail because we had an Arabic language running at the time which produces different plurals.

Ignore bools in plurals formatter.

---

src/SmartFormat.Tests/Extensions/ListFormatterTests.cs
src/SmartFormat/Extensions/ListFormatter.cs
src/SmartFormat/Extensions/ReflectionSource.cs

Fixes #313 for `ListFormatter`:
In `v1.6.1` a Selector was tested for having the name **"index"**, even if data was not an `IList`, and returned the `CollectionIndex`. This is now implemented again in the `ListFormatter.TryEvaluateSelector(...)`

ListFormatter handles selector name "Index" in IEnumerable and IList

---

appveyor.yml
src/Directory.Build.props

* Remove usage of Linq for less GC
* Add `IConvertable` support for `PluralLocalizationFormatter` and `ConditionalFormatter`
* `ListFormatter`
* ListFormatter handles selector name "Index" in `IEnumerable`s and `IList`s: In `v1.6.1` a Selector was tested for having the name **"index"**, even if data was not an `IList`, and returned the `CollectionIndex`. This is now implemented again in the `ListFormatter.TryEvaluateSelector(...)`
* Set the `ParentPlaceholder` property for item `Format`s
* Use `PooledObject<T>` where possible, so objects will be returned to `ObjectPool` also in case of exceptions
* `FormatItem.AsSpan()` returns the correct name
* Remove potential namespace collisions: All public types in namespace `Cysharp.Text` are now internal

Bump version to v3.2.0

---

appveyor.yml
src/Performance_v27/Performance_v27.csproj
src/SmartFormat.Tests/Extensions/PluralLocalizationFormatterTests.cs
src/SmartFormat.Tests/SmartFormat.Tests.csproj
src/SmartFormat/Extensions/PluralLocalizationFormatter.cs
src/SmartFormat/SmartFormat.csproj

Resolves #320 
* Fix: Throws FormattingException for Singular languages
* Add unit test for Singular language (Japanese)
* Auto detection only works with more than 1 format argument.
* Is recommended to set CanAutoDetect to false. This will be the default in a future version. Added xmdoc with this hint.

PluralLocalizationFormatter: Fix processing for Singular languages

---

src/SmartFormat.Tests/Extensions/PluralLocalizationFormatterTests.cs
src/SmartFormat/Utilities/PluralRules.cs

I added new Czech PluralRuleDelegate according to Czech grammar. It would break the usage of an old rule, however I don't believe it could have been used in real word. The test should be:
public void SmartFormatPluralTest()
{
var c = new CustomPluralRuleProvider(Czech);
string msg = "{0:plural:Nemáte zprávu|Máte {} zprávu|Přišly Vám {} zprávy|Přišlo Vám {} zpráv}!";
Smart.Format(c, msg, 0).Should().Be("Nemáte zprávu!");
Smart.Format(c, msg, 1).Should().Be("Máte 1 zprávu!");
Smart.Format(c, msg, 2).Should().Be("Přišly Vám 2 zprávy!");
Smart.Format(c, msg, 4).Should().Be("Přišly Vám 4 zprávy!");
Smart.Format(c, msg, 5).Should().Be("Přišlo Vám 5 zpráv!");
Smart.Format(c, msg, 6).Should().Be("Přišlo Vám 6 zpráv!");
}

Fix: PluralRules for Czech locale

---

.github/workflows/SonarCloud.yml
appveyor.yml
src/Directory.Build.props
src/SmartFormat.Tests/Extensions/PluralLocalizationFormatterTests.cs
src/SmartFormat/Extensions/PluralLocalizationFormatter.cs

Resolves #329
When `PluralLocalizationFormatter.CanAutoDetect == true`, values that are not convertible to `decimal` will throw then trying to `IConvertible.ToDecimal(...)`
When `PluralLocalizationFormatter.CanAutoDetect == true`, for values that are not convertible to `decimal`, `IFormatter.TryEvaluateFormat(...)` will return `false`
@karljj1 Makes sense?

Fix: Auto-detection of PluralLocalizationFormatter does not throw for values not convertible to decimal

---

src/SmartFormat/Core/Parsing/Parser.cs
src/SmartFormat/Core/Settings/ParserSettings.cs
src/SmartFormat/Extensions/ChooseFormatter.cs
src/SmartFormat/SmartFormatter.cs

* Replace ICollection.Any(...) with ICollection.Exists(...)
* Replace ICollection.All(...) with ICollection.TrueForAll(...)

Linq optimizations

---

src/SmartFormat.Tests/SmartFormat.Tests.csproj

Test code has already been updated as described below.
Note 1:
* ReSharper prior to v2023.3.2 may not recognize NUnit 4 tests. The VS2022 Test Explorer, however, shows the tests.
Note 2:
* NUnit v4 has breaking changes compared to v3.
* NUnit.Analyzer has rules and associated code fixes. This must be done while working on v3. The analyzers only run when the code compiles.

Bump NUnit package reference to v4.0.1

---

src/SmartFormat.Tests/Extensions/PluralLocalizationFormatterTests.cs
src/SmartFormat/Extensions/CustomPluralRuleProvider.cs
src/SmartFormat/Extensions/PluralLocalizationFormatter.cs
src/SmartFormat/Utilities/PluralRules.cs

PluralRule for DualFromZeroToTwo: Does not cover value of 2
The `Dictionary<string, PluralRuleDelegate> IsoLangToDelegate` is backed by a default dictionary. It can be restored with `PluralRules.RestoreDefault()` if one of the delegates was changed. Both has global effect.
Extract class `CustomPluralRuleProvider` to its own file
`PluralRuleDelegate DualFromZeroToTwo`:
* with 3 words, the index is for counts of 0, > 0 and < 2, more than 2
* with 4 words, the index is for counts of 0, > 0 and < 2,  >= 2 and < 3, more than 3
Add unit tests

PluralRule for DualFromZeroToTwo: Does not cover value of 2 - Closes #369

---

appveyor.yml
src/SmartFormat/ZString/ZStringBuilder.cs
src/SmartFormat/ZString/ZStringWriter.cs

* Flag `ZStringBuilder` and `ZStringWriter`with `[ExcludeFromCodeCoverage]`
* Add AltCoverAttributeFilter="ExcludeFromCodeCoverage" in CI tests

Exclude ZString wrappers from code coverage

---

src/SmartFormat/SmartFormat.csproj

Target framework entry in SmartFormat.csproj was overriding Directory.Build.propsy.Build.props

Fix: Remove target framework entry in SmartFormat.csproj

---

src/SmartFormat/Extensions/ChooseFormatter.cs
src/SmartFormat/Extensions/DictionarySource.cs
src/SmartFormat/Extensions/IsMatchFormatter.cs
src/SmartFormat/Extensions/WellKnownExtensionTypes.cs
src/SmartFormat/SmartFormat.csproj
src/SmartFormat/ZString/ZStringWriter.cs

Fix nullability issues caused by net60 target framework

Enable net60 for project SmartFormat

---

.github/workflows/SonarCloud.yml
appveyor.yml
src/Demo/Sample Extensions/RTFOutput.cs
src/Directory.Build.props
src/Performance/Performance.csproj
src/Performance_v27/Performance_v27.csproj
src/SmartFormat.Extensions.Newtonsoft.Json/SmartFormat.Extensions.Newtonsoft.Json.csproj
src/SmartFormat.Extensions.System.Text.Json/SmartFormat.Extensions.System.Text.Json.csproj
src/SmartFormat.Extensions.Time/SmartFormat.Extensions.Time.csproj
src/SmartFormat.Extensions.Xml/SmartFormat.Extensions.Xml.csproj
src/SmartFormat.Net/SmartFormat.Net.csproj
src/SmartFormat.Tests/SmartFormat.Tests.csproj
src/SmartFormat/Core/Formatting/FormattingException.cs
src/SmartFormat/Core/Output/StringOutput.cs
src/SmartFormat/Core/Output/TextWriterOutput.cs
src/SmartFormat/Core/Parsing/EscapedLiteral.cs
src/SmartFormat/Core/Parsing/ParsingErrors.cs
src/SmartFormat/Core/Settings/PoolSettings.cs
src/SmartFormat/Extensions/LocalizationFormattingException.cs
src/SmartFormat/Pooling/PoolingException.cs
src/SmartFormat/SmartFormat.csproj

* Add `net8.0` as target framework
* Update target framework `net461` to `net462`
* Mark CTOR overload `(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)` as obsolete (like it is in net8.0).
* Update proprocessor directives for target frameworks and NuGet packages
* Change appveyor_build_worker_image to Ubuntu2204 (image has net8.0 installed)

feat: Add net8.0 as a target framework

---

appveyor.yml

Set correct TFM for .NET 6.0 in CI for test coverage and corresponding coverage.*.xml

chore: Correct TFM for .NET 6.0 in CI

---

src/SmartFormat/SmartFormat.csproj

Remove redundant DependsOnTargets to SmartFormat.ZString.dll (remnant after moving to v3.4.0)

chore:: Remove redundant DependsOnTargets

---

src/SmartFormat/SmartFormat.csproj

Remove redundant DependsOnTargets from SmartFormat.csproj (a remnant after v3.4.0)

chore: Remove redundant DependsOnTargets

---

src/SmartFormat.Tests/Pooling/CollectionPoolTests.cs
src/SmartFormat.Tests/Pooling/ConcurrentPoolingTests.cs
src/SmartFormat.Tests/Pooling/DictionaryPoolTests.cs
src/SmartFormat.Tests/Pooling/HashSetPoolTests.cs
src/SmartFormat.Tests/Pooling/ListPoolTests.cs
src/SmartFormat.Tests/Pooling/ObjectPoolClassesTests.cs
src/SmartFormat.Tests/Pooling/StringBuilderPoolTests.cs
src/SmartFormat.Tests/Pooling/StringOutputPoolTests.cs
src/SmartFormat/Pooling/ObjectPools/LinkedPool.cs
src/SmartFormat/Pooling/ObjectPools/ObjectPool.cs
src/SmartFormat/Pooling/ObjectPools/ObjectPoolConcurrent.cs
src/SmartFormat/Pooling/ObjectPools/ObjectPoolSingleThread.cs
src/SmartFormat/Pooling/PoolRegistry.cs
src/SmartFormat/Pooling/SmartPools/FormatDetailsPool.cs
src/SmartFormat/Pooling/SmartPools/FormatPool.cs
src/SmartFormat/Pooling/SmartPools/FormattingInfoPool.cs
src/SmartFormat/Pooling/SmartPools/LiteralTextPool.cs
src/SmartFormat/Pooling/SmartPools/ParsingErrorsPool.cs
src/SmartFormat/Pooling/SmartPools/PlaceholderPool.cs
src/SmartFormat/Pooling/SmartPools/SelectorPool.cs
src/SmartFormat/Pooling/SmartPools/SplitListPool.cs
src/SmartFormat/Pooling/SmartPools/StringOutputPool.cs
src/SmartFormat/Pooling/SpecializedPools/CollectionPool.cs
src/SmartFormat/Pooling/SpecializedPools/DictionaryPool.cs
src/SmartFormat/Pooling/SpecializedPools/HashSetPool.cs
src/SmartFormat/Pooling/SpecializedPools/ListPool.cs
src/SmartFormat/Pooling/SpecializedPools/SpecializedPoolAbstract.cs
src/SmartFormat/Pooling/SpecializedPools/StringBuilderPool.cs

* Mark instance property `ObjectPool.IsPoolingEnabled` as obsolete in favor of `SmartSettings.IsPoolingEnabled`
* Simplify pooling classes, especially when creating new pools
* Make methods and their names more consistent

refactor: Internal SmartFormat.Pooling classes

---

src/SmartFormat.Tests/Core/FormatCacheTests.cs
src/SmartFormat/Core/Parsing/Parser.cs
src/SmartFormat/SmartFormatter.cs

* feat: Ensure, that the `Format` returned from internal string parsing gets returned to object pool
* refactor: Add static method to create `FormattingInfo` using object pool, and remove redundant private `SmartFormatter.Format(FormatDetails, Format, object?)`
* docs: Update xmldoc and comments in `Parser` and `SmartFormatter`
* test: Add missing unit tests for `SmartFormatter.Format` overload

feat: Ensure Format instances get returned to object pool

---

src/SmartFormat.Tests/Core/ParserTests.cs
src/SmartFormat/Core/Parsing/Format.cs
src/SmartFormat/Core/Parsing/Parser.cs
src/SmartFormat/Extensions/ListFormatter.cs

Closes  #415
* `Format.HasNested` checks Items for existing `Placeholder`
* Update Format Class Initialization (mark overload with arg `bool hasNested` as obsolete

feat: Format.HasNested checks for existing Placeholder in Items

---

src/SmartFormat.Tests/Extensions/DictionarySourceTests.cs
src/SmartFormat.Tests/Extensions/ReflectionSourceTests.cs
src/SmartFormat/Extensions/DictionarySource.cs
src/SmartFormat/Extensions/ReflectionSource.cs

Closes #425
* Modified `ReflectionSource.TypeCache` to be static, shared across all instances.
* Implemented a control mechanism for the size of `ReflectionSource.TypeCache`. When the cache exceeds the maximum size limit, it now removes the oldest entry first, adhering to a First-In-First-Out (FIFO) strategy.
* Enhanced documentation for `CaseSensitivityType.CaseInsensitive`: Clarified that in scenarios where multiple members share the same name but differ in case, the first encountered member will be selected.
* Correction: Ensured that generic dictionaries and dynamic objects respect the case sensitivity settings.
* Added to the documentation: Specified that the cache for `IReadOnlyDictionary` is deliberately scoped to the instance level.

feature: ReflectionSource and DictionarySource

---

.github/workflows/CheckWikiUpdates.yml
.github/workflows/Wiki_Update_Issue_Template.md
src/SmartFormat.Tests/Extensions/DefaultFormatterTests.cs
src/SmartFormat.Tests/ZString/ZCharArrayTests.cs
src/SmartFormat/Extensions/DefaultFormatter.cs
src/SmartFormat/ZString/ZCharArray.cs

Closes #422 
* Implement `ISpanFormattable` for `DefaultFormatter`
* Remove usage of stack buffer for `ISpanFormattable` in ZCharArray
* Make `IFormatProvider` an optional argument in `ZCharArray.Write(...)` overloads
* Add unit tests
```CSharp
// Performance test case
Smart.FormatInto(output, null, _placeholder0005Format, 1234567.890123f, 1234567.890123f, 1234567.890123f, 1234567.890123f, 1234567.890123f);
```
```
BenchmarkDotNet v0.13.12, Windows 11 (10.0.22631.3737/23H2/2023Update/SunValley3)
13th Gen Intel Core i7-13700K, 1 CPU, 24 logical and 16 physical cores
.NET SDK 8.0.302
[Host]   : .NET 8.0.6 (8.0.624.26715), X64 RyuJIT AVX2
.NET 8.0 : .NET 8.0.6 (8.0.624.26715), X64 RyuJIT AVX2
Job=.NET 8.0  Runtime=.NET 8.0
| Method                   | N     | Mean          | Error       | …
```

Implement ISpanFormattable for DefaultFormatter

---

src/SmartFormat.Extensions.System.Text.Json/SmartFormat.Extensions.System.Text.Json.csproj
src/SmartFormat.Tests/SmartFormat.Tests.csproj

* Bump System.Text.Json to v8.0.4
* A vulnerability exists in .NET when calling the JsonSerializer.DeserializeAsyncEnumerable method against an untrusted input using System.Text.Json may result in Denial of Service.
* See details: https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
Dependency updates to ensure compatibility and stability.
Updated package versions to maintain compatibility and stability.
- `SmartFormat.Extensions.System.Text.Json.csproj`: Updated `System.Text.Json` from `8.0.3` to `8.0.4`.
- `SmartFormat.Tests.csproj`: Updated `Microsoft.NET.Test.Sdk` from `17.9.0` to `17.10.0` and `NUnit3TestAdapter` from `4.5.0` to `4.6.0`.

Denial of Service Vulnerability in System.Text.Json < 8.0.4

---

src/SmartFormat.Extensions.System.Text.Json/SmartFormat.Extensions.System.Text.Json.csproj

Microsoft is releasing this security advisory to provide information about a vulnerability in System.Text.Json 6.0.x and 8.0.x. This advisory also provides guidance on what developers can do to update their applications to remove this vulnerability.
In System.Text.Json 6.0.x and 8.0.x, applications which deserialize input to a model with an [ExtensionData] property can be vulnerable to an algorithmic complexity attack resulting in Denial of Service.

Microsoft Security Advisory CVE-2024-43485

---

src/SmartFormat.Tests/SmartFormat.Tests.csproj

Updated the following NuGet packages:
- Microsoft.NET.Test.Sdk from 17.10.0 to 17.11.1
- NUnit from 4.1.0 to 4.2.2
- NUnit.Analyzers from 4.2.0 to 4.3.0
- FluentAssertions from 6.12.0 to 6.12.1
These updates include bug fixes, performance improvements, and new features.

Update dependencies in SmartFormat.Tests

---

src/SmartFormat.Tests/Extensions/SmartExtensionsTests.cs
src/SmartFormat/SmartExtensions.cs

Enable chaining from StringBuilder.AppendSmart() and StringBuilder.AppendLineSmart()

---

src/SmartFormat.Extensions.System.Text.Json/SmartFormat.Extensions.System.Text.Json.csproj
src/SmartFormat.Tests/SmartFormat.Tests.csproj
src/SmartFormat/SmartFormat.csproj

* Updated `System.Text.Json` to `9.0.0` in `SmartFormat.Extensions.System.Text.Json.csproj`.
* Updated `Microsoft.NET.Test.Sdk` to `17.12.0`, `NUnit.Analyzers` to `4.4.0`, and `FluentAssertions` to `7.0.0` in `SmartFormat.Tests.csproj`.
* Updated `System.Memory` to `4.6.0` in `SmartFormat.csproj`.

Update package versions in project files

---

src/SmartFormat.Tests/Extensions/ConditionalFormatterTests.cs
src/SmartFormat/Extensions/ConditionalFormatter.cs

Small bug one of our users flagged.
The `decimal` was being parsed using the current culture which could cause parsing issues.

[Conditional Formatter] Use invariant decimal parsing 

---

.github/workflows/SonarCloud.yml
appveyor.yml
src/Directory.Build.props
src/SmartFormat.Tests/Extensions/IsMatchFormatterTests.cs
src/SmartFormat.Tests/SmartFormat.Tests.csproj

* Bump version to v3.5.2
* Update NUnit v4.2.2 to v4.3.0
Fix unit test that was using `Is.EqualTo` instead of `Is.EquivalentTo` for an `IEnumerable` object

Bump version to v3.5.2

---

src/SmartFormat.Extensions.Time/TimeFormatter.cs
src/SmartFormat.Extensions.Time/Utilities/TimeSpanUtility.cs
src/SmartFormat.Extensions.Time/Utilities/TimeTextInfo.cs
src/SmartFormat.Tests/Extensions.Time/TimeFormatterTests.cs

Implementation of #458.
Since many languages needs to know if it is the last item/unit in the list in order to choose the correct separator, I had to change from using the `StringBuilder` to first build a list of the items/unit outputs and then combine them.

Add support for specifying separator between units when using TimeFormatter

---

src/SmartFormat.Extensions.Time/Resources/de.json
src/SmartFormat.Extensions.Time/Resources/en.json
src/SmartFormat.Extensions.Time/Resources/es.json
src/SmartFormat.Extensions.Time/Resources/fr.json
src/SmartFormat.Extensions.Time/Resources/it.json
src/SmartFormat.Extensions.Time/Resources/pt.json
src/SmartFormat.Extensions.Time/SmartFormat.Extensions.Time.csproj
src/SmartFormat.Extensions.Time/TimeFormatter.cs
src/SmartFormat.Extensions.Time/Utilities/CommonLanguagesTimeTextInfo.cs
src/SmartFormat.Extensions.Time/Utilities/FileName.cs
src/SmartFormat.Extensions.Time/Utilities/TimeSpanUtility.cs
src/SmartFormat.Tests/Extensions.Time/TimeFormatterTests.cs

- `SmartFormat.Extensions.Time.csproj` includes `System.Text.Json`.
- Enhance `TimeFormatter` to handle `TimeOnly` type (in supported frameworks).
- Update `CommonLanguagesTimeTextInfo` to load data from JSON resources and marked old properties as obsolete.
- Add JSON resource files for de, en, es, fr, it, pt languages.
- Introduce `TimeTextInfoData` struct to read localization data from JSON
- Update and add tests in `TimeFormatterTests`.

Refactor TimeFormatter

---

src/SmartFormat.Tests/Core/FormatterTests.cs
src/SmartFormat.Tests/Extensions/ChooseFormatterTests.cs
src/SmartFormat.Tests/Extensions/ConditionalFormatterTests.cs
src/SmartFormat.Tests/Extensions/ListFormatterTests.cs
src/SmartFormat.Tests/Extensions/PluralLocalizationFormatterTests.cs
src/SmartFormat/Core/Parsing/Parser.cs
src/SmartFormat/Smart.cs
src/SmartFormat/SmartFormatter.cs

- Removed `ThreadStatic` attribute from the `Smart.Default` instance of `SmartFormatter`.
- Added `Parallel` unit tests ensuring thread-safe operations with shared `SmartFormatter` instances with different `Smart.Extensions`.
- Updated documentation in `Parser.cs`, `Smart.cs`, and `SmartFormatter.cs` to clarify thread safety of methods.

Make `SmartFormatter.Format(...)` methods thread-safe

---

.github/workflows/Publish.yml

This change makes the workflow branch-agnostic and ensures we are building exactly what the version tag points to, regardless of which branch it was created from. It removes the former limitation to the `main` branch.

Make `Publish` workflow branch-agnostic

---

.github/workflows/CodeQuality.yml

Changed the `runs-on` property in the `build` job from `windows-latest` to `windows-2022` for a more specific Windows runner version during the build process.

Update Windows runner version in SonarCloud.yml
